version: '3.7'

services:
  #database
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=solidCrudApi
    volumes:
      - pg-data:/bitnami/postgresql
  
volumes:
  pg-data: